# Generated by Django 4.2.3 on 2024-01-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('keywords', models.JSONField()),
            ],
        ),
    ]
