# Generated by Django 4.2.3 on 2024-02-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to='core.newsarticle'),
        ),
    ]
