# Generated by Django 4.2.3 on 2024-03-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_daily_email_opt_in_user_preferences'),
        ('core', '0003_user_bookmarked'),
    ]

    operations = [
    ]
